FROM almalinux:8
#docker images --filter label=TRAINER=satish
LABEL   TRAINER="satish" \
        COURSE="DevOps" \
        DURATION="3 months" \
        # To specify the contact details of the people or organization responsible for the image
        org.opencontainers.image.authors="kalari@outlook.com"
